## Exception handling

An exception is a problem that arises during the execution of a program. A C# exception is a response to an exceptional circumstance that arises while a program is running.


Exceptions provide a way to transfer control from one part of a program to another. C# exception handling is built upon four keywords: **try**, **catch**, **finally**, and **throw**.

-   **try** − A try block identifies a block of code for which particular exceptions is activated. It is followed by one or more catch blocks.
    
-   **catch** − A program catches an exception with an exception handler at the place in a program where you want to handle the problem. The catch keyword indicates the catching of an exception.
    
-   **finally** − The finally block is used to execute a given set of statements, whether an exception is thrown or not thrown. For example, if you open a file, it must be closed whether an exception is raised or not.
    
-   **throw** − A program throws an exception when a problem shows up. This is done using a throw keyword.









### ref
https://www.tutorialspoint.com/csharp/csharp_exception_handling.htm

https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/exceptions/exception-handling

https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/exceptions/
